#!/usr/bin/env bash
# Script that configures an Ubuntu server so that localhost resolves to 127.0.0.2
# and facebook.com resolves to 8.8.8.8

sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
